<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="3_navigate_to_teacher"
    errors="1" failures="0" hostname="" id="" package="3_navigate_to_teacher" skipped="0"
    tests="1" time="0.005000" timestamp="Wed, 22 Aug 2018 22:00:22 GMT">
  
    <testcase name="Los estudiantes login falied" classname="3_navigate_to_teacher" time="0.005000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [3 Navigate To Teacher / Los estudiantes login falied]:

  ReferenceError: cy is not defined
    at Object.Los estudiantes login falied (/home/jdguzmans/Documents/workspace/automated-testing-workshop-2/4_nightwatch/tests/3_navigate_to_teacher.js:8:11)
    at Module.call (/usr/lib/node_modules/nightwatch/lib/runner/module.js:62:34)
    at /usr/lib/node_modules/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/usr/lib/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /usr/lib/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/usr/lib/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/usr/lib/node_modules/nightwatch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
